---
## - "Item Id,Meta Data/Damage,Count,Enchant Id-Enchant lvl,Custom Name"

##Enchantment ID's VVV
##https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/item/enchantment/Enchantment.php

##You can only put a total of 27 items in Items:

## "2,0,1,,name" Do this if you do not want an enchantment but want a name

Items:
- "263,0,64"
- "322,0,20"
- "264,0,64"
- "466,0,5"
- "130,0,10"
- "146,0,10"
- "47,0,32"
- "389,0,10"
- "138,0,10"
- "368,0,5"
- "432,0,5"
- "19,0,64"
- "30,0,20"
- "352,0,64"
- "174,0,32"
- "338,0,64"
- "80,0,64"
- "122,0,1"
- "201,0,64"
- "35,0,64"
- "332,0,64"
- "347,0,1"
- "20,0,64"
- "444,0,1"
- "170,0,64"
- "384,0,10"
- "450,0,1"
...
