---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "§a§l♪§e ‒ §aLand §6Of §bAnime§e ‒ §a♪"
OutdatedClient:
  custom: true
  message: "&cMáy khách MCPE của bạn đã lỗi thời!"
OutdatedServer:
  custom: true
  message: "&cRất tiếc! Máy chủ lỗi thời!"
WhitelistedServer:
  custom: true
  message: "&c&oMáy chủ này được đưa vào danh sách trắng!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "&2Thank! 
 &a{PLAYER}&d Đã Vào Server."
Join:
  hide: false
  custom: true
  message: "&e&lBạn &f{PLAYER}&e Đã Vào Server!!!\n&6-&e Nhớ Vote  Ủng Hộ Server Nha &f{PLAYER}&e !!! tại website: bit.do/animevote"
Quit:
  hide: false
  custom: true
  message: "&e&lBạn &f{PLAYER}&e Đã Out Vì Sợ Mẹ Gank =))"
WorldChange:
  enable: true
  message: "&eBạn &a{PLAYER}&e Đã Phóng Từ &6{ORIGIN}&e Qua &6{TARGET}"
Death:
  hide: true
  custom: true
  message: "&e{PLAYER} Tự Tử :<"
  death-contact-message:
    hide: false
    custom: true
    message: "&cOh! {PLAYER} Đã bị giết bởi {BLOCK} =))"
  kill-message:
    hide: false
    custom: true
    message: "&9{PLAYER} &eĐã bị giết bởi &c{KILLER} :V "
  death-projectile-message:
    hide: false
    custom: true
    message: "&c&l{PLAYER} Đã bị giết bởi {KILLER} by arrow"
  death-suffocation-message:
    hide: false
    custom: true
    message: "&c{PLAYER} chết ngạt"
  death-fall-message:
    hide: false
    custom: true
    message: "&c{PLAYER} rơi từ nơi cao"
  death-fire-message:
    hide: false
    custom: true
    message: "&c{PLAYER} bị cháy"
  death-on-fire-message:
    hide: false
    custom: true
    message: "&c{PLAYER} bị đốt cháy"
  death-lava-message:
    hide: false
    custom: true
    message: "&c{PLAYER} cố gắng bơi trong dung nham"
  death-drowning-message:
    hide: false
    custom: true
    message: "&c{PLAYER} chết đuối"
  death-explosion-message:
    hide: false
    custom: true
    message: "&c{PLAYER} phát nổ"
  death-void-message:
    hide: false
    custom: true
    message: "&c{PLAYER} rơi vào khoảng trống"
  death-suicide-message:
    hide: false
    custom: true
    message: "&c{PLAYER} tự sát"
  death-magic-message:
    hide: false
    custom: true
    message: "&c{PLAYER} đã bị giết bởi một câu thần chú"
...
